services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/challenge
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - 8080:8080
  db:
    image: 'mysql/mysql-server:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=challenge
    ports:
      - 3306:3306